name: Unit

on:
  workflow_call:
    inputs:
      test-suite:
        required: true
        type: string
      fail-fast:
        required: false
        type: boolean
        default: true
      test-timeout:
        required: false
        type: number
        default: 15

  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'resources/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'resources/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
      - 'psalm.xml'

jobs:
  test:
    timeout-minutes: 4
    runs-on: ${{ matrix.os }}
    concurrency:
      cancel-in-progress: true
      group: testing-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.php-version }}-${{ matrix.dependencies }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        dependencies:
          - lowest
          - locked
          - highest
    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v5

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: error_reporting=E_ALL

      - name: 🤖 Validate composer.json and composer.lock
        run: composer validate --ansi --strict

      - name: 📥 Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: 🧪 Run tests
        run: composer test
